include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.config.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    one_member_abstracts: ignore
